CREATE TABLE laliga.general_stats_24_25 (
	rk int,
	player varchar(100),
	nation varchar(50),
	pos varchar(10),
	squad varchar(50),
	age int,
	born int,
	mp int,
	starts int,
	minutes int,
	ninety_s float,
	gls int,
	ast int,
	g_plus_a int,
	g_minus_pk int,
	pk int,
	pkatt int,
	crdy int,
	crdr int,
	xg float,
	npxg float,
	xag float,
	npxg_plus_xag float,
	prgc int,
	prgp int,
	prgr int,
	gls_per_90 float,
	ast_per_90 float,
	g_plus_a_per_90 float,
	g_minus_pk_per_90 float,
	g_plus_a_minus_pk_per_90 float,
	xg_per_90 float,
	xag_per_90 float,
	xg_plus_xag_per_90 float,
	npxg_per_90 float,
	npxg_plus_xag_per_90 float,
	matches varchar(50)
);

	