CREATE TABLE laliga.passing_stats_24_25 (
	rk int,
	player varchar(100),
	nation varchar(50),
	pos varchar(10),
	squad varchar(50),
	age int,
	born int,
	ninety_s float,
	cmp int,
	att int,
	cmp_pct_ float,
	totdist int,
	prgdist int,
	short_cmp int,
	short_att int,
	short_cmp_pct_ float,
	med_cmp int,
	med_att int,
	med_cmp_pct_ float,
	long_cmp int,
	long_att int,
	long_cmp_pct_ float,
	ast int,
	xag float,
	xa float,
	a_minus_xag float,
	kp int,
	final_3rd int,
	ppa int,
	crspa int,
	prgp int,
	matches varchar(50)
);
	